
import React, { useState, useRef, useEffect } from 'react';
import { ChatMessage, PersonTotal } from '../types';

interface ChatPaneProps {
  messages: ChatMessage[];
  onSendMessage: (text: string) => void;
  totals: PersonTotal[];
  isProcessing: boolean;
  currency: string;
}

const ChatPane: React.FC<ChatPaneProps> = ({ messages, onSendMessage, totals, isProcessing, currency }) => {
  const [input, setInput] = useState('');
  const [copied, setCopied] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isProcessing) return;
    onSendMessage(input);
    setInput('');
  };

  const copySummary = () => {
    const text = totals.map(p => 
      `*${p.name}*: ${currency}${p.total.toFixed(2)}\n(${p.items.join(', ')})`
    ).join('\n\n');
    
    const summary = `🧾 *SplitSmart AI Summary*\n\n${text}\n\nGenerated by SplitSmart AI`;
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex flex-col h-full bg-slate-50 overflow-hidden relative">
      {/* Header with Live Split Summary */}
      <div className="p-5 bg-white border-b border-slate-200 shadow-sm z-10">
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Live Settlement</h3>
          {totals.length > 0 && (
            <button 
              onClick={copySummary}
              className={`text-[10px] font-bold px-3 py-1.5 rounded-full transition-all flex items-center gap-1.5 ${
                copied ? 'bg-green-100 text-green-700' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
              }`}
            >
              {copied ? 'Copied!' : 'Copy Summary'}
              <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>
            </button>
          )}
        </div>
        
        <div className="flex gap-3 overflow-x-auto pb-2 scrollbar-hide">
          {totals.length === 0 ? (
            <div className="flex-1 text-center py-4 bg-slate-50 border border-dashed border-slate-200 rounded-xl">
              <span className="text-xs text-slate-400 font-medium italic">Assign items to see split breakdown</span>
            </div>
          ) : (
            totals.map((p, i) => (
              <div key={i} className="flex-shrink-0 bg-white border-2 border-slate-100 rounded-2xl p-4 shadow-sm min-w-[140px] hover:border-blue-500/30 transition-colors">
                <div className="text-[10px] font-black text-blue-600 uppercase tracking-tight mb-0.5 truncate">{p.name}</div>
                <div className="text-xl font-black text-slate-900 tracking-tighter">{currency}{p.total.toFixed(2)}</div>
                <div className="mt-2 flex items-center gap-1">
                  <div className="w-3 h-3 bg-slate-100 rounded-full flex items-center justify-center text-[8px] font-bold">{p.items.length}</div>
                  <span className="text-[9px] text-slate-400 font-bold uppercase">Items</span>
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      {/* Chat History */}
      <div ref={scrollRef} className="flex-1 overflow-y-auto p-6 space-y-6">
        <div className="flex justify-center">
          <span className="text-[10px] font-bold bg-slate-200 text-slate-500 px-3 py-1 rounded-full uppercase">Today</span>
        </div>
        
        {messages.length === 0 && (
          <div className="flex flex-col items-center justify-center py-10 opacity-30 grayscale">
            <div className="text-4xl mb-2">💬</div>
            <p className="text-xs font-bold uppercase tracking-widest">Start chatting to split</p>
          </div>
        )}

        {messages.map((msg, i) => (
          <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div className={`max-w-[85%] p-4 rounded-2xl text-sm font-medium leading-relaxed ${
              msg.role === 'user' 
                ? 'bg-slate-900 text-white rounded-tr-none shadow-xl shadow-slate-200' 
                : 'bg-white text-slate-800 border border-slate-200 rounded-tl-none shadow-sm'
            }`}>
              {msg.text}
            </div>
          </div>
        ))}
        {isProcessing && (
          <div className="flex justify-start">
            <div className="bg-white p-4 rounded-2xl border border-slate-200 rounded-tl-none shadow-sm">
              <div className="flex gap-1.5">
                <div className="w-2 h-2 bg-slate-300 rounded-full animate-bounce"></div>
                <div className="w-2 h-2 bg-slate-300 rounded-full animate-bounce [animation-delay:0.2s]"></div>
                <div className="w-2 h-2 bg-slate-300 rounded-full animate-bounce [animation-delay:0.4s]"></div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Input Field */}
      <div className="p-6 bg-white border-t border-slate-200 pb-8">
        <form onSubmit={handleSubmit} className="relative group">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            disabled={isProcessing}
            placeholder="Type a command (e.g. 'Sarah had the steak')"
            className="w-full bg-slate-100 border-2 border-transparent rounded-2xl py-4 px-6 pr-14 text-sm font-semibold focus:bg-white focus:border-blue-500 transition-all outline-none shadow-inner"
          />
          <button 
            type="submit"
            disabled={!input.trim() || isProcessing}
            className="absolute right-3 top-1/2 -translate-y-1/2 w-10 h-10 bg-blue-600 text-white rounded-xl flex items-center justify-center hover:bg-blue-700 transition-all hover:scale-105 active:scale-95 disabled:opacity-30 disabled:grayscale shadow-lg shadow-blue-200"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><line x1="22" y1="2" x2="11" y2="13"></line><polygon points="22 2 15 22 11 13 2 9 22 2"></polygon></svg>
          </button>
        </form>
        <div className="flex flex-wrap justify-center gap-2 mt-4">
           {['"Everyone shared the nachos"', '"Remove beer from Alex"', '"Alice had the salad"'].map((tip, i) => (
             <button 
               key={i}
               onClick={() => setInput(tip.replace(/"/g, ''))}
               className="text-[9px] font-black uppercase tracking-tight text-slate-400 border border-slate-200 px-2.5 py-1 rounded-lg hover:border-slate-300 hover:text-slate-500 transition-colors"
             >
               {tip}
             </button>
           ))}
        </div>
      </div>
    </div>
  );
};

export default ChatPane;
